### ISSUE TITLE
Remove Raw files

### ISSUE THREAD

**Issue by HrushikeshK** [sudeepb02/Linuxication-mcug#8]
Remove these files:  #7 

- [ ]  [Linuxication-mcug/make/make-example/..gitignore.swp](https://github.com/sudeepb02/Linuxication-mcug/blob/master/make/make-example/..gitignore.swp)

- [ ] [Linuxication-mcug/make/.Makefile.swo](https://github.com/sudeepb02/Linuxication-mcug/blob/master/make/.Makefile.swo)

**Comment by sudeepb02** [comment]
Done
